### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by luperezsal** [ayushdabra/drone-images-semantic-segmentation#1]
Hello!

Would it be possible to have the trained model available? I am unable to reproduce the previous steps of the training phase in the Jupyter Notebook due to the augmented image paths to disk.

Thanks in advance.

Best regards

**Comment by ayushdabra** [comment]
Hi Luis! Please share your email id.

**Comment by luperezsal** [comment]
Thanks for your quick response Ayush.

My email is luis.perezsalagp@gmail.com

Thank you very much and greetings.

**Comment by steviereyes** [comment]
Hey Ayush, is it possible to share the pre-trained model with me as well? I am having a hard time reproducing the steps of the training phase as well. I think it might be the version of the libraries I am using but I am not exactly sure.

Regards

**Comment by ayushdabra** [comment]
Hi @steviereyes! Sorry for the late reply. Please share your email-id.

**Comment by Seyed-Ali-Ahmadi** [comment]
Hey Ayush,
The repo is great and detailed. Thank you.
Would you please share the pretrained weights with me?
My email address is cpt.ahmadisnipilo@gmail.com .

Thanks

**Comment by steviereyes** [comment]
@ayushdabra  No problem at all! Thank you for your help. My email address is: fortuitousfruition@gmail.com

**Comment by whitewalker11** [comment]
@ayushdabra  Great repo 
Would you please share the pretrained weights with me?
My email address is santoshwar.dhruv11@gmail.com

**Comment by koriavinash1** [comment]
@ayushdabra could you please share the pre-trained model with me as well? (avin.kori.re@gmail.com)
Thank you,
Avinash

**Comment by JimHanarose** [comment]
Hi @ayushdabra, could you please share the pre-trained model with me as well? here's my e-mail (jimhanarose84@gmail.com)
Thank you,
Jim

**Comment by amichayfeldman** [comment]
Hi @ayushdabra , 
may you share the pre trained weights with me?
amichayfeldman@gmail.com

Thank you!

**Comment by miraientpreneur** [comment]
Hi @ayushdabra ,
Thank you for your great work.
Could you please share the pretrained weights with me?

mail:  16169@sc.ac.kr

Thank you!

**Comment by UQ-DongYuan** [comment]
Hi @ayushdabra,
Thanks for your great work!
I'm wondering if you can share the pretrained weights with me.

mail: yuandong960123@gmail.com

Cheers!

**Comment by xiashengqing** [comment]
Hi @ayushdabra,
Really thanks for your great effort in presenting such a great and detailed repo!
Could you please share the pretrained weights with me?
My email address: xia170@purdue.edu

Thanks!

**Comment by Mengke-Yuan** [comment]
Hi @ayushdabra,
Really thanks for your great effort in presenting such a great and detailed repo!
Could you please share the pretrained weights with me?
My email address: [mannix.yuan@gmail.com](mailto:mannix.yuan@gmail.com)

Thanks!

**Comment by fatbringer** [comment]
Hey @ayushdabra thanks for sharing the great work.
I do not have sufficiently strong hardware to train.
Could you please share the pretrained weights with me?
My email address is yeokiatnern@gmail.com

**Comment by hassan-mehmood1** [comment]
Hi @ayushdabra, could you please share the pre-trained model with me as well? here's my e-mail (Hassan66169@gmail.com)
Thank you,
Hassan

**Comment by dembski21** [comment]
Hi @ayushdabra ,
Thank you for your great work.
Could you please share the pretrained weights with me?

mail: daviddembski2345@gmail.com

Thank you!

**Comment by li-bowen-official** [comment]
Hello @ayushdabra, could you share the best pretrained .h5 weights with me, thank you! My email is official.li.bowen@gmail.com

Also curious why you did not include the widely requested file on the repo by default for convenient replication and testing of your notebook.

**Comment by lcfdiniz** [comment]
Hello @ayushdabra! Congratulations for the great work here.

Could you please share the trained weights with me? Email: lcfdiniz@outlook.com

Thanks!

**Comment by RaviRockz** [comment]
please kindly,
can you share your trained model?

**Comment by ritalatuha** [comment]
Hi @ayushdabra ,
Is it possible to share the pretrained weights? (email: ritalatuha@gmail.com)

**Comment by ritalatuha** [comment]
Hi @ayushdabra ,
Is it possible to share the pretrained weights? (email: ritalatuha@gmail.com)

**Comment by atrazeynepbahceci** [comment]
Hello @ayushdabra ,
Could you please share the pre-trained weights with me? (my e-mail is: bahceciatra@gmail.com) Thanks!

**Comment by Qentolyen** [comment]
Hi @ayushdabra ,
Is it possible to share the pretrained weights? (email: [qentoyen4@wsanec.com](mailto:qentoyen4@wsanec.com))

**Comment by gersonponce** [comment]
Hello 
Is it posible to share trainend model? (email: gersonmponce@gmail.com) thanks !

**Comment by gersonponce** [comment]
Hello
Is it posible to share trainend model? (email: [gersonmponce@gmail.com](mailto:gersonmponce@gmail.com)) thanks !

**Comment by atztao** [comment]
Hello @ayushdabra ,
Could you  share the pre-trained model? (e-mail : [atztao@gmail.com](mailto:atztao@gmail.com)) Thanks!

**Comment by haichuanW** [comment]
Hello, is it possible to share pretrained model? email: wanghaichuan941221@gmail.com

**Comment by protaxY** [comment]
Hello @ayushdabra ,
Could you please share the pre-trained weights with me? (my e-mail is: [protaxy1302@gmail.com](protaxy1302@gmail.com)) Thanks!

**Comment by palffybalazs** [comment]
Hello @ayushdabra @Mengke-Yuan  @gersonponce @koriavinash1 
Could you please share the pre-trained weights with me? (my e-mail is: palffybalazs@sztaki.hu) Thanks!

**Comment by murrdpirate** [comment]
Hi @ayushdabra , Could you please share the pre-trained weights with me? My email is kmurra11@gmu.edu thank you!

**Comment by oguzhannysr** [comment]
Hi @ayushdabra , Could you please share the pre-trained weights with me? My email is 216791.oy@gmail.com
